const messagesEn = {


    fw_1: "raise",
    fw_2: "Listing",
    fw_3: "Currency",
    fw_4: "Total circulation",
    fw_5: "Marketing budget",
    fw_6: "Market liquidity",
    fw_7: "Community users",
    fw_8: "Introduction",
    fw_9: "wait",
    fw_10: "Start time",
    fw_11: "End time",
    fw_12: "price",
    fw_13: "number",
    fw_14: "publish time",
    fw_15: "Total issuance",
    fw_16: "Total circulation",
    fw_17: "white paper",
    fw_18: "Official website",
    fw_19: "Block query",
    fw_20: "Introduction",
    fw_21: "End",
    fw_22: "raise",
    fw_23: "Review",
    fw_24: "Wait",
    fw_25: "Recruit",
    fw_26: "EndOf",



    fw_27: "name",
    fw_28: "Please enter the contact name",
    fw_29: "phone number",
    fw_30: "Please enter the contact phone number",
    fw_31: "Currency Chinese",
    fw_32: "Please enter the Chinese name of the currency",
    fw_33: "Currency English",
    fw_34: "Please enter the English name of the currency",
    fw_35: "Total circulation",
    fw_36: "Please enter the total currency issuance",
    fw_37: "Market liquidity",
    fw_38: "Please enter the currency in circulation",
    fw_39: "Community users",
    fw_40: "Please enter the number of community users",


    fw_41: "Marketing budget",
    fw_42: "Please enter marketing budget",
    fw_43: "Project Introduction",
    fw_44: "Please briefly describe the content of the project",
    fw_45: "Application",
    fw_46: "Please fill in the contact person",
    fw_47: "please fill in cell phone number",
    fw_48: "Please fill in Chinese name",
    fw_49: "Please fill in the English name",
    fw_50: "Please fill in the total issuance",


    fw_51: "Please fill in the market circulation",
    fw_52: "Please fill in the number of community users",
    fw_53: "Please fill in the marketing budget",
    fw_54: "Please fill in the project introduction",
    fw_55: "Successful application",
    fw_56: "price",

    fw_57: "Mining Pool",
    fw_58: "Profit Record",
    fw_59: "Mining Pool Assets Conversion",
    fw_60: "Put into",
    fw_61: "Yesterday",
    fw_62: "Promote",
    fw_63: "Time",
    fw_64: "Mining Pool List",
    fw_65: "Money holding",
    fw_66: "Promote",
    fw_67: "Time",
    fw_68: "Cumulative Income",
    fw_69: "Best",
    fw_70: "Minimum",


    fw_71: "Cumulative Income",
    fw_72: "Select Currency",
    fw_73: "Time Stamp Income",
    fw_74: "Date",
    fw_75: "Amount",
    fw_76: "Cancel",

    fw_77: "Amount of input",
    fw_78: "Please enter the number of coins invested in the mining pool",
    fw_79: "All",
    fw_80: "Transaction Password",
    fw_81: "Please enter the transaction password",
    fw_82: "Google Verification",
    fw_83: "Please enter Google verification",
    fw_84: "Verification Code",
    fw_85: "Please enter the verification code",
    fw_86: "Available Quantity",
    fw_87: "Real Time Scale",
    fw_88: "Confirm investment",
    fw_89: "Into the mining pool equivalent",
    fw_90: "Successful investment",

    fw_91: "Promote Miners",
    fw_92: "Deadline total dug out",
    fw_93: "Holding",
    fw_94: "Promotional",
    fw_95: "Time",
    fw_96: "Amount of personal",
    fw_97: "Coins held by the team",
    fw_98: "Promotion power",
    fw_99: "Promoting Miners",
    fw_100: "Time stamp",
    fw_101: "Redemption",


    //otc
    fw_102: "Coins",
    fw_103: "fiat currency",
    fw_104: "I want to buy",
    fw_105: "I want to sell",
    fw_106: "Quantity",
    fw_107: "Limit",
    fw_108: "Deal",
    fw_109: "Unit Price",
    fw_110: "Buy",
    fw_111: "Sale",
    fw_112: "Cancel",
    fw_113: "Purchase amount (CNY)",
    fw_114: "Amount sold (USDT)",
    fw_115: "All",
    fw_116: "Limit",
    fw_117: "Transaction Quantity",
    fw_118: "Transaction Amount",
    fw_119: "Buy Now",
    fw_120: "Sell Now",
    fw_121: "Buy Amount",
    fw_122: "Buy Quantity",



    //otcDetials
    fw_123: "Order Details",
    fw_124: "Pending Order",
    fw_125: "Closed in the last 30 days",
    fw_126: "Transaction Amount",
    fw_127: "Order Number",
    fw_128: "Transaction Quantity",
    fw_129: "Transaction Price",
    fw_130: "Order pending order",
    fw_131: "The buyer needs to accept the order first",
    fw_132: "If you miss an order within minutes, it will be cancelled automatically",
    fw_133: "Pending Payment",
    fw_134: "No payment within minutes, automatic cancellation",
    fw_135: "No payment within minutes, automatic cancellation",
    fw_136: "Payer's Name",
    fw_137: "Payment Method",
    fw_138: "Alipay",
    fw_139: "WeChat",
    fw_140: "Bank Card",
    fw_141: "Order Remarks",
    fw_142: "Contact Buyer",
    fw_143: "Cancel order",
    fw_144: "Accept order",
    fw_145: "Appeal Order",
    fw_146: "Confirm the payment",
    fw_147: "Buyer Email",
    fw_148: "Copy",
    fw_149: "Please enter the reason for appeal",
    fw_150: "A staff member will intervene after submitting the appeal, please be patient",
    fw_151: "Please enter the reason for appeal",
    fw_152: "Cancel",
    fw_153: "OK",
    fw_154: "Prompt",
    fw_155: "Are you sure to cancel?",
    fw_156: "Are you sure to take the order?",
    fw_157: "Are you sure you have received the payment?",
    fw_158: "Minutes",
    fw_159: "Second",
    fw_160: "Please accept the order first",

    fw_161: "The seller needs to accept the order first",
    fw_162: "Online Banking Remittance",
    fw_163: "Payee Account Name",
    fw_164: "Account opening bank of the payee",
    fw_165: "Account opening address of the payee",
    fw_166: "Payee Account",
    fw_167: "Copy",
    fw_168: "For the safety of your funds, please use your own",
    fw_169: "Bank Account",
    fw_170: "Make a transfer.",
    fw_171: "The operation of using any payment method other than the account is deemed invalid.",
    fw_172: "Click the reduced QR code on the right to scan the QR code to pay",
    fw_173: "Payment Remarks",
    fw_174: "(Please fill in)",
    fw_175: "Remarks",
    fw_176: "Contact Seller",
    fw_177: "Confirm payment",
    fw_178: "Seller Email",
    fw_179: "Are you sure you have paid?",

    //otcRecord
    fw_180: "Transaction History",
    fw_181: "Sell",
    fw_182: "Buy",
    fw_183: "Total Amount",
    fw_184: "Quantity",
    fw_185: "Buy",
    fw_186: "Sale",
    fw_187: "In progress",
    fw_188: "Completed",
    fw_189: "Cancelled",
    fw_190: "Appeal",


    //publish
    fw_191: "Post an ad",
    fw_192: "I want to sell coins",
    fw_193: "I want to buy coins",
    fw_194: "Select transaction",
    fw_195: "Select currency",
    fw_196: "The price is between",
    fw_196_1: '',
    fw_197: "Price",
    fw_198: "Quantity",
    fw_199: "Please enter quantity",
    fw_200: "Available",
    fw_201: "Minimum  amount",
    fw_202: "Fill minimum amount",
    fw_203: "Input greater than ",
    fw_204: "Input less than ",
    fw_205: "Remarks",
    fw_206: "Transaction Method",
    fw_207: "UnionPay",
    fw_208: "Alipay",
    fw_209: "WeChat",
    fw_210: "Fund Password",
    fw_211: "Please enter the fund password",
    fw_212: "Google Verification",
    fw_213: "Please enter Google verification",
    fw_214: "Verification Code",
    fw_215: "Please enter the verification code",
    fw_216: "Notes",
    fw_217: "Please be sure to confirm receipt after receiving the payment",
    fw_218: "Please verify the source of funds and transfer remarks to avoid bank cards being frozen by the bank",
    fw_219: "Publish Now",
    fw_220: "select currency",
    fw_221: "Please enter the quantity",
    fw_222: "Please enter your remarks information",
    fw_223: "Select Currency",
    fw_224: "Cancel",
    fw_225: "Fiat currency unit",
    fw_226: "Not open to buy yet",
    fw_227: "Not yet open for sale",
    fw_228: "Please enter the price",
    fw_229: "Please enter the quantity",
    fw_230: "Please enter the minimum quantity",
    fw_231: "Please enter the maximum number",
    fw_232: "The maximum quantity shall not be less than the minimum quantity",
    fw_233: "Please set the payment method",


    //publishList
    fw_234: "Release Record",
    fw_235: "Buy",
    fw_236: "Sell",
    fw_237: "Cancel",
    fw_238: "Remove",
    fw_239: "On Shelf",
    fw_240: "Cancelled",
    fw_241: "Quantity",
    fw_242: "Total Amount",
    fw_243: "Prompt",
    fw_244: "Are you sure to cancel?",
    fw_245: "OK",
    fw_246: "Confirm",
    fw_247: "Hold it?",
    fw_248: "In progress",
    fw_249: "Completed",
    fw_250: "OK",

    fw_251: "Block Explorer",






    fw_252: 'Enter the received verification code',
    fw_253: 'the verification code has been sent to:',


    fw_254: 'Please enter the mobile number to bind',
    fw_255: 'Mobile phone binding',
    fw_256: 'Please input your mobile phone number',
    fw_257: 'Picture saved successfully',
    fw_258: "Image save failed",
    fw_259: 'loading',
    fw_260: 'Please fill in the quantity first',
    fw_261: 'Please fill in the user name',
    fw_262: 'Please fill in the password',
    fw_263: 'User does not exist',
    fw_264: 'Please fill in the email address',
    fw_265: 'Please fill in the transaction password',
    fw_266: 'Please fill in the SMS verification code',
    fw_267: 'Please fill in the email verification code',
    fw_268: 'Have you saved the mnemonics?',
    fw_269: 'save next time',
    fw_270: 'saved',
    fw_271: 'Go to the home page',
    fw_272: 'Copy mnemonics',
    fw_273: 'Mnemonics',
    fw_274: 'For your account security,',
    fw_275: 'Please copy the mnemonics and keep them well to avoid economic losses',
    fw_276: 'Registration successful',
    fw_277: 'Your account number',
    fw_278: 'Mobile phone number modification',
    fw_279: 'old phone number',
    fw_280: 'new phone number',
    fw_281: 'Please enter a new mobile number',
    fw_282: "New mobile phone verification code",
    fw_283: 'Help details',
    fw_284: "login authentication settings",
    fw_285: 'Google verification code',
    fw_286: 'The application acceptor needs to pledge',
    fw_287: 'Are you sure you want to apply?',
    fw_288: 'Authentication in progress',
    fw_289: 'Please enter the content',
    fw_290: 'Please enter a title',
    fw_291: 'Please input quantity or amount',
    fw_292: "3 transactions have been cancelled in total on the same day. You can't buy any more on that day",
    fw_293: "Buyer's phone number",
    fw_294: 'Confirm release',
    fw_295: 'Please be sure to log in to the online bank or a third-party account number to confirm receipt of the money',
    fw_296: "Seller's phone number",
    fw_297: 'Confirm cancellation',
    fw_300: 'Cancel rule',
    fw_301: 'If the buyer cancels 3 orders in the same day, it will limit the purchase function of that day',
    fw_302: 'Payment confirmation',
    fw_303: 'Please confirm that you pay the seller. Malicious click will directly freeze the account',
    fw_304: 'Confirm to leave payment',
    fw_305: 'If you have paid, please click "confirm payment"',
    fw_306: 'The order will be in',
    fw_307: 'Cancel after timeout',
    fw_308: 'No payment, leave',
    fw_309: 'Please select the payment method',
    fw_310: 'Transaction details',
    fw_311: 'Cancel automatically if no order is received',
    fw_312: 'Automatic cancellation without payment',
    fw_313: 'Account opening address',
    fw_314: 'Click the QR code icon on the right to scan the code to pay',
    fw_315: 'Determine the complaint',
    fw_316: 'Please enter your question',
    fw_317: 'Please confirm the order before operation',
    fw_318: 'After cancellation, the order cannot be resumed',
    fw_319: 'Confirm receipt',
    fw_320: 'Please confirm that the order is correct and click OK',
    fw_321: 'You have cancelled the order receiving operation',
    fw_322: 'Cancel successfully',
    fw_323: 'Updating',
    fw_324: 'Please enter your nickname',
    fw_325: 'Nickname of coin dealer',
    fw_326: 'The minimum number of transactions should be greater than:',
    fw_327: "The maximum number of transactions should be less than:",
    fw_328: 'The number of transactions should be greater than:',
    fw_329: 'Hot currency',
    fw_330: 'Subscription',
    fw_331: 'Flash cash',
    fw_332: 'Vote',
    fw_333: ' Zone',
    fw_334: 'Flash sale',
    fw_335: 'new',
    fw_336: 'Click collapse',
    fw_337: 'Click to expand',
    fw_338: 'DeFi is an abbreviation of the phrase decentralized finance. It allows anyone in the world to conduct financial activities without geographic or time limits by building decentralized agreements for open financial systems.',
    fw_339: 'DeFi is divided into many tracks based on its role in financial activities, including:',
    fw_340: 'DeFi Loans',
    fw_341: 'Asset lending and borrowing services are provided to users with decentralized lending agreements. Users with idle assets can obtain income by lending assets, while users with asset borrowing needs can borrow assets and carry out other financial activities without verification.',
    fw_342: 'Predictor',
    fw_343: 'Provide a benchmark price for decentralized lending. Users of in decentralized loans can lend or borrow based on the price of the predictor to avoid losses resulted by price deviating from the markets.',
    fw_344: 'DiFi Exchange',
    fw_345: 'An exchange that does not require registration to trade and is more anonymous than a centralized exchange. But the liquidity is weaker compared with centralised exchanges.',
    fw_346: 'No currency information at present!',

    fw_347: 'To subscribe',
    fw_348: 'To trade',
    fw_349: 'No more data available',

    fw_350: 'Voting rules',
    fw_351: 'Vote on coin',
    fw_352: 'Participating currency',
    fw_353: 'Currency details',
    fw_354: (num)=> `Voted ${num}`,
    fw_355: 'Vote succeeded',
    fw_356: 'Payment wallet',
    fw_357: 'Coin purse',
    fw_358: 'Wallet balance',
    fw_359: 'Payment amount',
    fw_360: 'Votes cast',
    fw_361: 'Current votes',
    fw_362: 'Before voting begins',
    fw_363: 'Till the end of voting',
    fw_364: 'Vote now',
    fw_365: 'Wait to start',
    fw_366: 'End of activity',
    fw_367: 'Confirm vote',
    fw_368: 'Details',
    fw_369: 'Activity ended',
    fw_370: 'Activity not started',
    fw_371: 'Voting has reached its limit',
    fw_372: 'Insufficient balance in wallet',
    fw_373: 'My rush',
    fw_374: 'Activity',
    fw_375: 'Start time',
    fw_376: 'Total',
    fw_377: 'Surplus',
    fw_378: 'End time',
    fw_379: 'Buy it now',
    fw_380: 'Time limited currency purchase',
    fw_381: 'End of the event',
    fw_382: 'Unit price of rush purchase',
    fw_383: 'Enter integer quantity',
    fw_384: 'Surplus',
    fw_385: 'Upper limit of quantity',
    fw_386: 'Real time news',
    fw_387: 'User',
    fw_388: 'Quantity of rush purchase',
    fw_389: 'Rush to confirm',
    fw_390: 'Flash buying ',
    fw_391: 'Trading hours',
    fw_392: num=>`Robbed ${num}`,
    fw_393: 'My subscription',
    fw_394: 'Prophecy machine',
    
    fw_395: 'Unit price',
    fw_396: 'Confirm subscription',
    fw_397: 'Number of subscription',
    fw_398: 'Maximum purchase',
    fw_399: 'Remaining purchases',
    fw_400: 'Enter integer subscription quantity',
    fw_401: 'Subscribe now',
    fw_402: 'Time limited subscription activity',
    fw_403: 'Real time subscription news',
    fw_404: 'Subscription information',
    fw_405:  num=>`Reserved ${num}`,
    fw_406: 'Issuing time',
    fw_407: 'None',
    fw_408: 'You can also subscribe',
    fw_409: 'Cancellation',
    fw_410: 'Make an appointment now',
    fw_411: 'Confirm addition',
    fw_412: 'Are you sure you want to cancel the appointment?',
    fw_413: 'Think again',
    fw_414: 'Subscription failed',
    fw_415: 'To be issued',
    fw_416: 'Subscription successful',
    fw_417: 'Booking',
    fw_418: 'Total',
    fw_419: 'Consensus area',
    fw_420: 'Consensus rules',
    fw_421: 'Holding consensus calculation',
    fw_422: 'See my consensus',
    fw_423: 'Reject',
    fw_424: 'Connect',
    fw_425: 'Consensus calculation',
    fw_426: 'My quantity',
    fw_427: "Are you sure you want to reject the other party's consensus connection invitation? ",
    fw_428: 'OK reject',
    fw_429: 'Connect consensus',
    fw_430: 'Number of connections required',
    fw_431: 'Total payment',
    fw_432: 'Confirm connection',
    fw_433: 'Release consensus',
    fw_434: 'Invite consensus',
    fw_435: 'Total amount of originations',
    fw_436: num => `Minimum quantity ${num}`,
    fw_437: 'Invitee account',
    fw_438: 'Please enter the invited account',
    fw_439: 'OK to publish',
    fw_440: 'Initiate invitation',
    fw_441: 'Put consensus community into the consensus community and find consensus partners',
    fw_442: 'Invite friends to agree and make profits together',
    fw_443: 'Invited me',
    fw_444: name => `Converted pool assets (${name}) `,
    fw_445: 'Cumulative income',
    fw_446: 'Consensus income',
    fw_447: 'Connected',
    fw_448: 'Times accelerating',
    fw_449: num => `Disconnect will deduct the consensus amount of ${num}%, are you sure to disconnect?`,
    fw_450: 'Consensus reached',
    fw_451: 'Invite friends',
    fw_452: 'Save picture to local',
    fw_453: 'Number of connected consensus',
    fw_454: 'Holding currency to calculate power',
    fw_455: 'Month',
    fw_456: 'Monthly revenue record',
    fw_457: 'Revenue type',
    fw_458: 'Revenue amount',
    fw_459: 'Number of initiated',
    fw_460: num => `The number of connections required is greater than ${num}`,
    fw_461: num => `My number is greater than ${num}`,
    fw_462: num => `The total consensus should be greater than ${num}`,
    fw_463: 'My consensus',
    fw_464: 'Invited',
    fw_465: 'Invitation',
    fw_466: 'Co connected',
    fw_467: 'Disconnect',
    fw_468: 'The consensus revenue',
    fw_469: 'Send invitation',
    fw_470: 'Are you sure you want to cancel the consensus? ',
    fw_471: 'Confirm to cancel',
    fw_472: name =>`Wait for friend (${name}) to reply to the invitation! `,
    fw_473: 'To be connected',
    fw_474: 'Connecting',
    fw_475: 'Disconnected',
    fw_476: 'Bonus rules',
    fw_477: 'Accumulated Bonus',
    fw_478: 'Bonus records',
    fw_479: 'Rank',
    fw_480: 'Bonus',
    fw_481: 'Bonus',
    fw_482: 'Monthly BonusBonus record',
    fw_483: 'Users (top 41 Awards)',
    fw_484: '',
    fw_485: '',
    fw_486: '',
    fw_487: '',
    fw_488: '',
    fw_489: '',
    fw_490: '',
    fw_491: '',
    fw_492: '',
    fw_493: '',
    fw_494: '',
    fw_495: '',
    fw_496: '',
    fw_497: '',


    text1: "Language Settings",
    text2: "Chinese",
    text3: "Exit",
    text4: "Logout successfully",
    text5: "click to copy",
    text6: "Account Management",
    text7: "Security Center",
    text8: "Payment Management",
    text9: "Announcement",
    text10: "About Us",
    text11: "Authentication",
    text12: "Uncertified",
    text13: "failed",
    text14: "Successful",
    text15: "Certifying",
    text16: "Help Center",
    text17: "Settings",
    text18: "Customer Service",
    text19: "Acceptor",
    text20: "Acceptor",
    text21: "Prompt",
    text22: "Apply for Acceptor?",
    text23: "Cancel",
    text24: "OK",
    text25: "Application is successful",
    text26: "About Us",
    text27: "Version number",
    text28: "User Agreement",
    text29: "Blockchain",
    text30: "Open Source Address",
    text31: "Developer Alliance",
    text32: "Version",
    text33: "Account Management",
    text34: "Current login account",
    text35: "Associated Account",
    text36: "Switch",
    text37: "Add Account",
    text38: "Delete",
    text39: "Delete successfully",
    text40: "Switching successfully",

    text41: "Account",
    text42: "Please enter an activated account",
    text43: "Login Password",
    text44: "Please enter the login password",
    text45: "Online time (days)",
    text46: "Select",
    text47: "Submit",
    text48: "Online Duration",
    text49: "Day",
    text50: "Please enter account",
    text51: "Please enter password",
    text52: "Added successfully",

    text53: "Mailbox binding",
    text54: "Working for your account",
    text55: "Please enter the mailbox number",
    text56: "Please enter again",
    text57: "Please enter the verification code",
    text58: "Confirm",
    text59: "Sent successfully",
    text60: "Send",
    text61: "Please enter email",
    text62: "Resend after s",
    text63: "Reacquire",
    text64: "The two mailboxes are different",
    text65: "Binding successful",

    text66: "authentication",
    text67: "Real name",
    text68: "Please enter your real name",
    text69: "Certificate Number",
    text70: "Please enter your ID number",
    text71: "Please upload the front photo of your ID card",
    text72: "Please upload the reverse photo of ID card",
    text73: "Please upload a photo of a handheld ID card",
    text74: "Reason for last authentication failure",
    text75: "Submit for review",
    text76: "Please upload a hand-held ID card and note photo",
    text77: "Submitted successfully",
    text78: "Loading",

    text79: "Modify Email",
    text80: "Old Email Code",
    text81: "New Mailbox",
    text82: "Please enter your new email address",
    text83: "New Email Code",
    text84: "Submit",
    text85: "Modified successfully",

    text86: "Modify login password",
    text87: "Please enter the old password",
    text88: "Please enter a new password",
    text89: "Please enter the new password again",
    text90: "Please enter the mnemonic phrase",
    text91: "Use mnemonic to modify",
    text92: "Use verification code to modify",
    text93: "Modify transaction password",
    text94: "Choice of Nationality",
    text95: "Please select a country",
    text96: "Search",

    text97: "Mine pool earnings yesterday",
    text98: "Not logged in",
    text99: "Click Jump to log in",
    text100: "Transfer",
    text101: "Pool",
    text102: "Books",
    text103: "Activate",
    text104: "RedEnvelope",
    text105: "Information",
    text106: "Raise",
    text107: "Community",
    text108: "SnapUp",
    text109: "Other",
    text110: "Performer",
    text111: "Currency",
    text112: "Price",
    text113: "Rise",
    text114: "volume",

    text115: "Total asset conversion",
    text116: "Gateway",
    text117: "Hide small",
    text118: "Search",
    text119: "Available",
    text120: "Freeze",
    text121: "Conversion",
    text122: "Currency",
    text123: "French",
    text124: "Pool",
    text125: "Currency account conversion",
    text126: "French account conversion",
    text127: "Pool account conversion",

    text128: "Account",
    text129: "Current login account",
    text130: "Associated account",
    text131: "Individual",
    text132: "Switch",
    text133: "Add account",
    text134: "Delete",

    //安全中心
    text135: "Security Center",
    text136: "Login modification",
    text137: "Transaction modification",
    text138: "Mailbox",
    text139: "modify",
    text140: "Mailbox",
    text141: "set up",

    text142: "Payment management",
    text143: "Alipay",
    text144: "Not enabled",
    text145: "Bank card",
    text146: "WeChat",
    text147: "Enabled",

    //添加支付宝
    text148: "Add Alipay",
    text149: "Name",
    text150: "Alipay account",
    text151: "Alipay payment QR code",
    text152: "Upload QR code",
    text153: "Show the opening mode",
    text154: "Submit",
    text155: "Please enter your real name",
    text156: "Please input your Alipay account",
    text157: "You do not have real name authentication",
    text158: "Please input your Alipay account",
    text159: "Uploading",
    text160: "Successfully",

    //添加银行卡
    text161: "Add bank card",
    text162: "Name",
    text163: "Please enter your real name",
    text164: "Bank of deposit",
    text165: "Please enter your bank of deposit",
    text166: "Bank card number",
    text168: "Please enter your bank card number",
    text169: "Account opening branch",
    text169: "Please enter your account opening branch",
    text170: "Show the opening mode",
    text171: "Submit",
    text172: "ICBC",
    text173: "CCB",
    text174: "ABC",
    text175: "PSBC",
    text176: "Bank of Communications",
    text177: "CMB",
    text178: "Bank of China",
    text179: "China Everbright Bank",
    text180: "China CITIC Bank",
    text181: "Shanghai Pudong Development Bank",
    text182: "China Minsheng Bank",
    text183: "Industrial Bank",
    text184: "Ping An Bank",
    text185: "Guangfa bank",
    text186: "Huaxia Bank",
    text187: "Cancel",
    text188: "Confirm",

    //添加微信
    text189: "Add wechat",
    text190: "Name",
    text191: "Please enter your real name",
    text192: "Wechat account",
    text193: "Please enter your wechat account",
    text194: "Wechat collection QR code",
    text195: "Upload QR code",
    text196: "Show the opening mode",
    text197: "Submit",

    text198: "Contact service",
    text199: "Feedback title",
    text200: "Please feedback title",
    text201: "Feedback content",
    text202: "Please input feedback",
    text203: 'Contact person (required)',
    text204: 'Please enter contact person',
    text205: 'Contact information (required)',
    text206: 'Please enter the contact information',
    text207: 'Submit',
    text208: 'Help list',
    text209: 'Notice',
    text210: 'Asset details',
    text212: 'Available',
    text213: 'Frozen',
    text214: 'Conversion',
    text215: 'Records',
    text216: 'Time',
    text217: 'Type',
    text218: 'Quantity',
    text219: 'Recharge',
    text220: 'Withdraw',
    text221: 'Transfer ',
    text222: 'Change',

    text223: 'Recharge',
    text224: 'Save QR code',
    text225: 'Recharge address',
    text226: 'Copy address',
    text227: 'Reminder of money replenishment',
    text228: 'Please do not add any non local currency assets to the above address, otherwise the assets will not be recovered',


    //充值记录
    text229: 'Recharge record',
    text230: 'Time',
    text231: 'Type',
    text232: 'Quantity',

    //转账
    text233: 'Transfer',
    text234: 'Records',
    text235: 'Selection',
    text236: 'Receiving',
    text237: 'Fill the account or address to transfer',
    text238: 'Quantity',
    text239: 'Fill the amount of transfer',
    text240: 'All',
    text241: 'Available',
    text242: 'Transaction password',
    text243: 'Fill transaction password',
    text244: 'Miner fee',
    text245: 'When transferring money, let the other party open the gateway of corresponding currency first',
    text246: 'Submit',
    text247: 'Select currency',
    text248: 'Transfer successful',

    text249: 'Miner fee',
    text250: 'Receiving',

    text251: 'Fill in userName',
    text252: 'Fill in login password',
    text253: 'Login',
    text254: 'Forget the password',
    text255: 'I don not account',
    text256: 'Create an account',


    //忘记密码
    text257: 'Forget password',
    text258: 'Fill userName',
    text259: 'Fill email address',
    text260: 'Fill verification code',
    text261: 'Fill mnemonic words',
    text262: 'Fill new login password',
    text263: 'Fill new login password again',
    text264: 'Modify with captcha',
    text265: 'Use mnemonics to modify',
    text266: 'Confirm',
    text267: 'The two passwords are different',

    text268: 'Transaction secret free',
    text269: 'Payment verification settings',
    text270: 'Verification',
    text271: 'Bound',

    text272: 'Transaction secret free',
    text273: 'Every time',
    text274: 'Secret free trading within 2 hours',
    text275: 'Secret free trading within 6 hours',
    text276: 'Secret free trading within 12 hours',
    text277: 'Never enter transaction validation',
    text278: 'Successful',
    text279: 'Payment settings',
    text280: 'Transaction password',
    text281: 'Transaction password + Google verification code',
    text282: 'Transaction password + email verification code ',
    text283: 'Transaction password + email verification code + Google verification code',

    text284: 'Create an account',
    text285: 'Username',
    text286: 'Enter user name (lowercase + number)',
    text287: 'Email',
    text288: 'Enter mailbox',
    text289: 'Please enter the verification code',


    text290: 'Next step',
    text291: 'Username is not standardized',


    text292: 'Password settings',
    text293: 'For the security of your account, please set the password for your account to avoid economic loss',
    text294: 'Login password',
    text295: 'Enter login password',
    text296: 'Enter login password',
    text297: 'Enter the login password again',
    text298: 'Enter the login password again',
    text299: 'Transaction password',
    text300: 'Enter your transaction password',
    text301: 'Enter your transaction password',
    text302: 'Enter your transaction password again',
    text303: 'Enter your transaction password again',
    text304: 'Confirmation',

    //提币
    text305: 'Withdraw',
    text306: 'Address',
    text307: 'Please enter the withdrawal address',
    text308: 'Address notes',
    text309: 'Please enter address remarks',
    text310: 'Number',
    text311: 'Please input the withdrawal amount',
    text312: 'All',
    text313: 'Available',
    text314: 'Transaction password',
    text315: 'Charge',
    text316: 'Notes on money withdrawal',
    text317: 'Minimum value of single withdrawal',
    text318: 'Maximum daily withdrawal',
    text319: 'Actual receipt quantity',
    text320: 'Confirm',
    text321: 'Sorry, your credit is running low',
    text322: 'Suspension of withdrawal',
    text323: 'Successful application',

    //提币地址
    text324: 'Withdrawal address',
    text325: 'Address',
    text326: 'Notes',
    text327: 'Tips',
    text328: 'Are you sure you want to delete this address',
    text329: 'cancel',
    text330: 'Confirm',
    text331: 'Deletion succeeded',

    text332: 'New address',
    text333: 'Withdrawal address',
    text334: 'Please enter the withdrawal address',
    text335: 'Address notes',
    text336: 'Please enter address remarks',
    text337: 'Verification Code',
    text338: 'Please enter the verification code',
    text339: 'Confirm',
    text340: 'Added successfully',

    //行情
    text341: 'Optional',
    text342: 'All',
    text343: 'Search currency',
    text344: 'Currency',
    text345: 'Price',
    text346: 'Rise',
    text347: 'Volume',

    //激活矿工
    text348: 'Activate miners',
    text349: 'Counter account',
    text350: 'Enter platform account or address',
    text351: 'Transaction password',
    text352: 'Enter transaction password',
    text353: 'Google Authenticator',
    text354: 'Enter Google verification',
    text355: 'Verification Code',
    text356: 'Input verification code',
    text357: 'Activation cost',
    text358: 'Confirm',
    text359: 'Activation successful',

    //账本
    text360: 'Books',
    text362: 'Currency',
    text363: 'French',
    text364: 'Pool',

    //划转
    text365: 'Change',
    text366: 'From',
    text367: 'To',
    text368: 'Currency',
    text369: 'Quantity',
    text370: 'All',
    text371: 'Select type',
    text372: 'Select currency',
    text373: 'The Fiat and the mine cannot be exchanged',
    text374: 'Successful transfer',
    text375: 'Available',

    text376: 'Record',
    text377: 'Time',
    text378: 'Type',
    text379: 'Quantity',

    text380: 'Record',
    text381: 'More services',


    //币币交易
    text382: 'Currency',
    text383: 'French',
    text384: 'Buy',
    text385: 'Sell',
    text386: 'Limited price',
    text387: 'Market price',
    text388: 'BuyPrice',
    text389: 'Current best price',
    text390: 'SellPrice',
    text391: 'BuyVolume',
    text392: 'SellVolume',
    text393: 'Using',
    text394: 'Amount',
    text395: 'Login',
    text396: 'Price',
    text397: 'Quantity',

    text398: 'Current ',
    text399: 'Cancel',
    text401: 'Actual',
    text402: 'Search currency',
    text403: 'Select currency',
    text404: 'Cancel',
    text405: 'Security verification',
    text406: 'Tips',
    text407: 'Are you sure you want cancel',
    text408: 'Security verification',

    text409: 'Tips',
    text410: 'Are you sure you want cancel',
    text412: 'Confirm',

    text413: 'Please enter the correct price and number',
    text414: 'Price is too different from the current transaction price',
    //历史委托

    text415: 'Historical',
    text416: 'Price',
    text417: 'Quantity',
    text418: 'Total',
    text419: 'No deal',
    text420: 'Completed',
    text421: 'No record',
    //募集
    text422: 'Raise',
    text423: 'Select payment currency',
    text424: 'Quantity',
    text425: 'Please input quantity',
    text426: 'Available ',
    text427: 'Price',

    //资讯
    text428: 'Information',
    text429: 'Open',
    text430: 'Pack up',
    text431: 'not enabled',

    //赎回
    text432: 'Redeem',
    text433: 'Redemption quantity',
    text434: 'Input redemption quantity',
    text435: 'All',
    text436: 'Available',
    text437: 'Conversion mine pool',
    text438: 'Confirm',
    text439: 'Successful',
    text440: 'You haven not turned on Google verification yet',

    text441: 'Receiving address',
    text442: 'Records',
    text443: 'Aiming at the QR code, you can automatically scan to the address bar',
    text444: 'Collection records',
    text445: 'Miner fee',
    text446: 'Transfer to account',
    text447: 'Not yet open',

    text448: 'User Settings',
    text449: 'Please set user name (lowercase letter + number)',
    text450: 'Please enter the binding mailbox',
    text451: 'Set login password',
    text452: 'Card',
    text453: 'Detail',


    text454: 'Add gateway',
    text455: 'Opening the gateway requires payment',
    text456: 'The gateway will open automatically within 10 minutes. If not, please contact online customer service',
    text457: 'Confirm',

    text458: 'buy quantity(USDT)',
    text459: 'Sell amount(CNY)',
    text460: 'Sell quantity(USDT)',
    text461: 'Sell Amount',
    text462: 'Sell Quantity',

    text463: 'Pool',
    text464: 'Put pool',
    text465: 'Redeem',
    text466: 'Redemption deduction charge',


    text467: 'Details',
    text468: 'Start raising',
    text469: 'Closing raising',
    text470: 'Raising price',
    text471: 'Target ',
    text472: 'Issue',
    text473: 'Total issue',
    text474: 'Circulation',
    text475: 'White paper',
    text476: 'Website',
    text477: 'Block',
    text478: 'Introduce',

    text479: 'SMS verification code',
    text480: 'Email verification code',

    text481: 'Cash earnings',
    text482: 'Promotion',
    text483: 'Address',

    text484: 'Google Authenticator',
    text485: 'Secret',
    text486: 'Copy',
    text487: 'Email verification code',
    text488: 'Please enter email verification code',
    text489: 'Google Authenticator',
    text490: 'Please enter Google verification',
    text491: 'Enable Google authentication',

    text492: 'Please do not recharge any non erc20-usdt assets to the above address, otherwise the assets will not be recovered.',
    text493: 'After recharging to the above address, you need to confirm the whole network node, and receive the account after 12 network confirmation. Currency can be withdrawn after 12 network confirmation.',
    text494: 'Minimum recharge amount:',
    text495: 'Recharge less than the minimum amount will not be posted and cannot be returned.',
    text496: 'Your recharge address will not change frequently, you can recharge repeatedly: if there is any change, we will try our best to inform you through network announcement or email.',
    text497: 'Please make sure that the computer and browser are secure to prevent information from being tampered with or leaked',


    text498: 'Recharge details',
    text499: 'Withdrawal details',
    text500: 'type',
    text501: 'General',
    text502: 'state',
    text503: 'Charge',
    text504: 'address',
    text505: 'time',
    text506: 'type',
    text507: 'state',
    text508: 'Recharge address',
    text509: 'time',
    text510: 'address',
    text511: 'General',
    text512: 'Illegal address',



    text513: 'please enter login password',
    text514: 'please enter login password',
    text515: 'Cancel',
    text516: 'Confirm',
    text517: 'not login',
    text518: 'login in to check',
    text519: 'Applying',
    text520: 'Rejected',
    text521: 'Prompt',
    text522: 'Apply acceptance,you need settings',
    text523: '1. Phone number binding',
    text524: '2.Authentication',
    text525: '3.Payment settings',
    text526: 'Set',
    text527: 'Conversion ',
    text528: 'Pledge ',
    text529: 'Increase',
    text530: 'Redemption',
    text531: 'Current pledge deposit has met the requirements',
    text532: 'I see',
    text533: 'redeem pledged',

    text534: 'current pledge amount',
    text535: 'after redemption, you will no longer be the acceptor',
    text536: 'redemption deducted',
    text537: 'Charge',
    text538: 'Add pledged',
    text539: 'Quality deposit of acceptor should reach',
    text540: 'advertising can published',
    text541: 'please enter the increase quantity',
    text542: 'current pledge amount',
    text543: 'please fill in the increased quantity',
    text544: 'added successfully',
    text545: 'Redemption application submitted successfully',

    text546: 'you have not set the contact information',
    text547: 'set now',
    text548: 'before selling, you need to transfer the currency to the French currency account. Do you want to transfer it',
    text549: 'transfer',
    text550: 'merchant authentication',
    text551: 'after you become an authorized merchant, you can get the right to publish advertisements',
    text552: 'apply now',
    text553: '3 transactions have been cancelled on the same day, and can not be purchased before 0:00 on that day',
    text554: 'got it',
    text555: 'Outstanding orders',

    text556: 'Quick money purchase',
    text557: 'Mobile phone number setting',











    update: 'new version found! ',
    update1: 'upgrade now',
    update2: 'update prompt',
    update4: 'please do not do other operations during update',
    Update: 'new version found! ',

}
export default messagesEn
